# Generated by Django 4.1.13 on 2024-02-26 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="mod_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="date published"
            ),
            preserve_default=False,
        ),
    ]
