# Generated by Django 4.1.13 on 2024-02-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0002_deck_mod_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="side",
        ),
        migrations.AddField(
            model_name="deck",
            name="description",
            field=models.CharField(default="deck", max_length=1000),
            preserve_default=False,
        ),
    ]
