# Generated by Django 4.1.13 on 2024-03-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("flashcards", "0003_remove_card_side_deck_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deck",
            name="mod_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
